language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - unit2 discover --pattern=test_*.py
  - flake8 rapiduino
