name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run type checking using Mypy
      run: poetry run mypy rapiduino
    - name: Run linting using Flake8
      run: poetry run flake8 rapiduino
    - name: Check code formatting using Black
      run: poetry run black --check --diff --color rapiduino
