name: Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test against Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests and generate test coverage report
        run: poetry run coverage run --source=rapiduino -m pytest tests
      - name: Submit test coverage report
        if: matrix.python-version == '3.9'
        uses: AndreMiras/coveralls-python-action@develop

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run type checking using Mypy
        run: poetry run mypy rapiduino tests
      - name: Run linting using Flake8
        run: poetry run flake8 rapiduino tests
      - name: Check code formatting using Black
        run: poetry run black --check --diff --color rapiduino tests
      - name: Check code formatting using isort
        run: poetry run isort --check --diff --color rapiduino tests
