name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test against Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Generate test coverage report
      run: poetry run coverage run --source=rapiduino -m pytest tests
    - name: Run tests and publish coverage
      run: poetry run pytest tests
    - name: Submit test coverage report
      if: ${{ matrix.python-version }} == 3.9
      uses: AndreMiras/coveralls-python-action@develop
    - name: Run type checking
      run: poetry run mypy rapiduino
    - name: Run linting
      run: poetry run flake8 rapiduino
